---
name: remove_comment_close_reopen
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/49614
rollout_issue_url: 
milestone: '13.7'
type: development
group: group::code review
default_enabled: false
