---
name: usage_data_full_code_quality_report_total
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/49079
rollout_issue_url:
milestone: '13.7'
type: development
group: group::testing
default_enabled: false
